Repository szmc-team/SickZil-Machine, pull requests merged in 2020-03, with the labels that each got.

#3 Feature/create basic setting
  web/.eslintrc
  web/.prettierrc
  web/config-overrides.js
  web/jest.config.js
  web/package.json
  web/yarn.lock
Labels: feature

#8 Add Topbar
  .DS_Store
  web/package.json
  web/src/App.tsx
  web/src/components/Topbar.tsx
  web/src/index.tsx
  web/yarn.lock
Labels: feature

#11 파일시스템 타이핑 및 예시 추가
  web/package.json
  web/src/index.tsx
  web/src/modules/index.ts
  web/tsconfig.json
  web/yarn.lock
Labels: feature

#10 기본 UI 코드 구조 작성
  web/.prettierrc
  web/config-overrides.js
  web/package.json
  web/src/App.tsx
  web/src/components/Topbar.tsx
  web/src/components/card/Card.tsx
  web/src/components/card/index.ts
  web/src/features/activity-bar/ActivityBar.tsx
  web/src/features/activity-bar/components/explorer/Explorer.tsx
  web/src/features/activity-bar/components/explorer/index.ts
  web/src/features/activity-bar/components/menu/Menu.tsx
  web/src/features/activity-bar/components/menu/MenuList.tsx
  web/src/features/activity-bar/components/menu/MenuListItem.tsx
  web/src/features/activity-bar/components/menu/index.ts
  web/src/features/activity-bar/index.ts
  web/src/features/app/App.tsx
  web/src/features/app/index.ts
  web/src/features/editor/Editor.tsx
  web/src/features/editor/index.ts
  web/src/features/status-bar/StatusBar.tsx
  web/src/features/status-bar/index.ts
  web/src/index.css
  web/src/index.tsx
  web/src/styles/GlobalStyle.tsx
  web/src/styles/ThemeContext.tsx
  web/src/styles/index.ts
  web/yarn.lock
Labels: feature

#12 jest 셋업
  web/.babelrc
  web/jest.config.js
  web/package.json
  web/src/core/NeuralNet.test.ts
  web/src/core/NeuralNet.ts
Labels: feature

#14 코어 디렉터리 구조 정리
  web/src/core/NeuralNet.ts
  web/src/core/file-manager/FileManager.ts
  web/src/core/file-manager/configureFileManager.ts
  web/src/core/file-manager/index.ts
  web/src/core/neural-net/NeuralNet.test.ts
  web/src/core/neural-net/NeuralNet.ts
  web/src/global.d.ts
  web/src/modules/index.ts
Labels: feature

#13 기본 레이아웃 변경
  web/package.json
  web/src/features/activity-bar/ActivityBar.tsx
  web/src/features/activity-bar/components/explorer/Explorer.tsx
  web/src/features/app/App.tsx
  web/src/features/editor/Editor.tsx
  web/src/features/menu-bar/MenuBar.tsx
  web/src/features/menu-bar/index.ts
  web/src/features/tool-bar/ToolBar.tsx
  web/src/features/tool-bar/index.ts
  web/yarn.lock
Labels: feature

#17 파일시스템 기본 기능 추가
  web/codegen.yml
  web/package.json
  web/src/core/file-manager/FileManager.ts
  web/src/core/file-manager/configureFileManager.ts
  web/src/features/activity-bar/ActivityBar.tsx
  web/src/features/activity-bar/components/explorer/Explorer.tsx
  web/src/features/activity-bar/components/explorer/ImageList.tsx
  web/src/features/activity-bar/components/explorer/ImageListItem.tsx
  web/src/global.d.ts
  web/src/graphql/configureClient.ts
  web/src/graphql/index.ts
  web/src/graphql/mutation/CreateFile.graphql
  web/src/graphql/operations.ts
  web/src/graphql/query/File.graphql
  web/src/graphql/resolvers/Mutation/index.ts
  web/src/graphql/resolvers/Query/index.ts
  web/src/graphql/resolvers/configureResolvers.ts
  web/src/graphql/resolvers/index.ts
  web/src/graphql/schema/Query.graphql
  web/src/graphql/types.ts
  web/src/index.tsx
  web/yarn.lock
Labels: feature

#19 파일 인터페이스 확장 & 절대경로 Import 추가
  web/codegen.yml
  web/config-overrides.js
  web/package.json
  web/src/core/file-manager/FileManager.ts
  web/src/features/activity-bar/components/explorer/Explorer.tsx
  web/src/features/activity-bar/components/explorer/ImageListItem.tsx
  web/src/features/activity-bar/components/explorer/types.ts
  web/src/graphql/configureClient.ts
  web/src/graphql/mutation/CreateFile.graphql
  web/src/graphql/mutation/CreateFileEntry.graphql
  web/src/graphql/mutation/DeleteFileEntry.graphql
  web/src/graphql/operations.ts
  web/src/graphql/query/File.graphql
  web/src/graphql/query/FileEntries.graphql
  web/src/graphql/query/FileEntry.graphql
  web/src/graphql/resolvers/Mutation/index.ts
  web/src/graphql/resolvers/Query/index.ts
  web/src/graphql/resolvers/configureResolvers.ts
  web/src/graphql/resolvers/fileEntry/Mutation.ts
  web/src/graphql/resolvers/fileEntry/Query.ts
  web/src/graphql/resolvers/fileEntry/index.ts
  web/src/graphql/schema/FileEntry.graphql
  web/src/graphql/schema/Query.graphql
  web/tsconfig.json
  web/tsconfig.path.json
  web/yarn.lock
Labels: feature

#21 기본 스타일링 적용
  web/src/components/card/Card.tsx
  web/src/components/card/index.ts
  web/src/contants.ts
  web/src/features/activity-bar/ActivityBar.tsx
  web/src/features/activity-bar/components/menu/Menu.tsx
  web/src/features/activity-bar/components/menu/MenuList.tsx
  web/src/features/activity-bar/components/menu/MenuListItem.tsx
  web/src/features/activity-bar/components/menu/index.ts
  web/src/features/activity-bar/index.ts
  web/src/features/app/App.tsx
  web/src/features/editor/Editor.tsx
  web/src/features/explorer/Explorer.tsx
  web/src/features/explorer/ImageList.tsx
  web/src/features/explorer/ImageListItem.tsx
  web/src/features/explorer/index.ts
  web/src/features/explorer/types.ts
  web/src/features/menu-bar/MenuBar.tsx
  web/src/features/menu-bar/components/ApplicationMenu.tsx
  web/src/features/menu-bar/components/EditorMenu.tsx
  web/src/features/menu-bar/components/EtcMenu.tsx
  web/src/features/status-bar/StatusBar.tsx
  web/src/features/tool-bar/ToolBar.tsx
  web/src/features/tool-bar/index.ts
  web/src/styles/GlobalStyle.tsx
  web/src/styles/ThemeContext.tsx
Labels: enhancement, feature

#24 github actions 추가
  .github/workflows/ci.yml
  .github/workflows/linux.yml
  README.md
  web/README.md
  web/package.json
  web/yarn.lock
Labels: feature

#29 테스트 설정 추가
  web/jest.config.js
  web/package.json
  web/src/core/neural-net/NeuralNet.test.ts
  web/src/features/explorer/Explorer.test.tsx
  web/src/features/explorer/Explorer.tsx
  web/src/features/explorer/components/ImageList.tsx
  web/src/features/explorer/components/ImageListItem.tsx
  web/src/graphql/resolvers/configureResolvers.ts
  web/yarn.lock
Labels: enhancement, wip
