Repository szmc-team/SickZil-Machine, pull requests merged in 2020-04, with the labels that each got.

#35 이미지 URL 추가
  web/jest.config.js
  web/package.json
  web/src/core/file-manager/FileManager.test.ts
  web/src/core/file-manager/FileManager.ts
  web/src/core/file-manager/configureFileManager.ts
  web/src/core/file-manager/index.ts
  web/src/features/explorer/Explorer.test.tsx
  web/src/features/explorer/Explorer.tsx
  web/src/graphql/configureClient.ts
  web/src/graphql/operations.ts
  web/src/graphql/query/FileEntries.graphql
  web/src/graphql/query/FileEntry.graphql
  web/src/graphql/schema/FileEntry.graphql
  web/src/setupTests.ts
  web/yarn.lock
Labels: enhancement, feature

#34 에디터에 캔버스 추가 및 이미지 가져오기
  web/.eslintrc
  web/package.json
  web/src/features/editor/Editor.test.tsx
  web/src/features/editor/Editor.tsx
  web/src/features/explorer/Explorer.test.tsx
  web/src/features/explorer/components/ImageListItem.tsx
  web/src/features/menu-bar/components/EditorMenu.tsx
  web/src/index.tsx
  web/src/store/configureStores.ts
  web/src/store/index.ts
  web/src/store/modules/editor/actions.ts
  web/src/store/modules/editor/epic.ts
  web/src/store/modules/editor/hooks.ts
  web/src/store/modules/editor/index.ts
  web/src/store/modules/editor/reducer.ts
  web/src/store/modules/editor/types.ts
  web/src/store/rootEpic.ts
  web/src/store/rootReducer.ts
  web/src/stores/modules/global/actions.ts
  web/src/stores/modules/global/index.ts
  web/src/stores/modules/global/reducer.ts
  web/yarn.lock
Labels: wip

#38 SegNet inference 함수 구현
  web/.gitignore
  web/package.json
  web/src/core/neural-net/NeuralNet.test.ts
  web/src/core/neural-net/NeuralNet.ts
  web/src/core/neural-net/image.test.ts
  web/src/core/neural-net/nodeUtils.ts
  web/src/mocks/half_life.png
  web/src/mocks/half_life_padded.png
  web/src/mocks/small16x.png
  web/yarn.lock
Labels: feature

#39 테스트 개선
  web/cypress.json
  web/cypress/fixtures/example.json
  web/cypress/fixtures/wk.png
  web/cypress/integration/file-management.js
  web/cypress/plugins/index.js
  web/cypress/support/commands.js
  web/cypress/support/index.js
  web/jest.config.js
  web/package.json
  web/src/features/explorer/components/ImageList.tsx
  web/src/features/explorer/components/ImageListItem.tsx
  web/src/features/menu-bar/components/ApplicationMenu.tsx
  web/yarn.lock
Labels: enhancement

#42 이미지 크기에 상관없이 마스크 생성
  web/src/core/neural-net/NeuralNet.test.ts
  web/src/core/neural-net/NeuralNet.ts
  web/src/core/neural-net/image.ts
  web/src/mocks/middle.png
  web/src/mocks/middle16x.png
  web/src/mocks/tiny16x.png
Labels: bug
